SELECT * FROM REGIONS;

SELECT FIRST_NAME, DEPARTMENT_ID, SALARY, LAST_NAME FROM EMPLOYEES;

SELECT EMPLOYEE_ID, EMAIL, (HIRE_DATE - 7) "One week before hire date"
FROM EMPLOYEES;

SELECT (FIRST_NAME || '(' || JOB_ID || ')') our_employees
FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

SELECT JOB_TITLE, ('min = ' || MIN_SALARY || ', max = ' || MAX_SALARY) AS info,
MAX_SALARY AS max, MAX_SALARY*2-2000 AS new_salary
FROM JOBS;

SELECT 'Peter''s dog is very clever' FROM DUAL;

SELECT Q'<Peter's dog is very clever>' FROM DUAL;

SELECT 100*365.25*24*60 FROM DUAL;