SELECT * FROM EMPLOYEES WHERE LENGTH(FIRST_NAME) > 10;

SELECT * FROM EMPLOYEES 
WHERE MOD (SALARY, 1000) = 0;
/* ѕожалуй вариант выше действительно логичнее и проще */
SELECT * FROM EMPLOYEES 
WHERE SALARY = ROUND(SALARY, -3);

SELECT PHONE_NUMBER, SUBSTR(PHONE_NUMBER, 1, 3) FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE ('___.___.____');

SELECT * FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME, -1) = 'm' AND LENGTH(FIRST_NAME) > 5;

SELECT NEXT_DAY(SYSDATE, 'ѕ€тница') FROM DUAL;

SELECT * FROM EMPLOYEES
WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) > 150;

SELECT REPLACE(PHONE_NUMBER, '.', '-') FROM EMPLOYEES;

SELECT UPPER(FIRST_NAME), LOWER(EMAIL), INITCAP(JOB_ID) FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME, SALARY) FROM EMPLOYEES;

SELECT HIRE_DATE, ROUND(HIRE_DATE, 'MM'), TRUNC(HIRE_DATE, 'YYYY') FROM EMPLOYEES;

SELECT RPAD(FIRST_NAME, 10, '$'), LPAD(LAST_NAME, 15, '!')
FROM EMPLOYEES;

SELECT FIRST_NAME, INSTR(FIRST_NAME, 'a', 1, 2) FROM EMPLOYEES;

/* BOTH можно не писать, это значение by default */
SELECT '!!!HELLO!! MY FRIEND!!!!!!!!', 
       TRIM(BOTH '!' FROM '!!!HELLO!! MY FRIEND!!!!!!!!')
FROM DUAL;

/* TRUNC(SALARY*3.1415, -3)/1000 - суть та же сама€, разница минимальна */
SELECT SALARY, SALARY*3.1415, ROUND(SALARY*3.1415), TRUNC(SALARY*3.1415/1000)
FROM EMPLOYEES;

SELECT HIRE_DATE, ADD_MONTHS(HIRE_DATE, 6), LAST_DAY(HIRE_DATE)
FROM EMPLOYEES;