SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'David';

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'FI_ACCOUNT';

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 AND SALARY > 4000;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (20, 30);

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_a%a';

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50, 80) AND COMMISSION_PCT IS NOT NULL 
ORDER BY 4;

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE ('%n%n%') OR FIRST_NAME LIKE ('N%n%');

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE ('%_____%')
ORDER BY DEPARTMENT_ID DESC NULLS LAST;
/* Так как функцию LENGTH к этому моменту ещё не проходили, 
    решать надо, как в примере выше.*/
SELECT * FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > 4
ORDER BY DEPARTMENT_ID DESC NULLS LAST;

SELECT * FROM EMPLOYEES
WHERE (SALARY BETWEEN 3000 AND 7000) AND (COMMISSION_PCT IS NULL) AND
    JOB_ID IN ('PU_CLERK', 'ST_MAN', 'ST_CLERK');

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE ('%\%%') ESCAPE '\';

SELECT JOB_ID, FIRST_NAME, SALARY FROM EMPLOYEES
WHERE EMPLOYEE_ID >= 120 AND JOB_ID != 'IT_PROG'
ORDER BY JOB_ID, FIRST_NAME DESC;