SELECT DEPARTMENT_ID, MIN(SALARY), MAX(SALARY), MIN(HIRE_DATE), MAX(HIRE_DATE), COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY COUNT(*) DESC;

SELECT SUBSTR(FIRST_NAME, 1, 1), COUNT(*)
FROM EMPLOYEES
GROUP BY SUBSTR(FIRST_NAME, 1, 1)
HAVING COUNT(*) > 1
ORDER BY COUNT(*);

SELECT DEPARTMENT_ID, SALARY, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, SALARY;

SELECT TO_CHAR(HIRE_DATE, 'DAY'), COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'DAY');

SELECT DEPARTMENT_ID 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 30 AND SUM(SALARY) > 300000;

SELECT REGION_ID
FROM COUNTRIES
GROUP BY REGION_ID
HAVING SUM(LENGTH(COUNTRY_NAME)) > 50;

SELECT JOB_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(DISTINCT JOB_ID) > 1;

SELECT DEPARTMENT_ID, JOB_ID, MAX(SALARY), MIN(SALARY) 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING AVG(SALARY) > 10000;

SELECT MANAGER_ID 
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL
GROUP BY MANAGER_ID
HAVING AVG(SALARY) BETWEEN 6000 AND 9000;

SELECT ROUND(MAX(AVG(SALARY)), -3)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;